export const QUERY_LOGIN_STATUS = 'QUERY_LOGIN_STATUS';

export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';

export const APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS';

export const USER_DATA_FETCHED = 'USER_DATA_FETCHED';

export const USER_DATA_FETCH_FAILED = 'USER_DATA_FETCH_FAILED';

export const GET_RECIPES = 'GET_RECIPES';
export const CREATE_RECIPE = 'CREATE_RECIPE';

export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const LOGGED_OUT = 'LOGGED_OUT';

export const USER_REGISTERED = 'USER_REGISTERED';


export const SEARCH_RECIPE_TITLE = 'SEARCH_RECIPE_TITLE';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';

export const USER_FOLLOWERS_FETCHED = 'USER_FOLLOWERS_FETCHED';
export const USER_FOLLOWING_FETCHED = 'USER_FOLLOWING_FETCHED';

export const USER_UNFOLLOWED = 'USER_UNFOLLOWED';
