export const QUERY_LOGIN_STATUS = 'QUERY_LOGIN_STATUS';

export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';

export const APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS';

export const USER_DATA_FETCHED = 'USER_DATA_FETCHED';

export const USER_DATA_FETCH_FAILED = 'USER_DATA_FETCH_FAILED';

export const GET_RECIPES = 'GET_RECIPES';

export const LOGGED_OUT = 'LOGGED_OUT';

export const USER_REGISTERED = 'USER_REGISTERED';
